### ISSUE TITLE
[Audit/7.11] Overview page

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/observability-design#12]
Related master audit issue https://github.com/elastic/observability-design/issues/7

### Empty state

- [x] I think we could do a better job in showing empty states. https://github.com/elastic/kibana/issues/85795
<img width="730" alt="Screenshot 2020-12-10 at 17 41 14" src="https://user-images.githubusercontent.com/20965076/101802449-b90b3600-3b0f-11eb-9e3a-60902d47bbe7.png">

**Comment by formgeist** [comment]
Closing - the enhancement issue has been created. Thanks @katrin-freihofner for doing the audit 👍
