### ISSUE TITLE
[Audit 7.11] Metrics

### ISSUE THREAD

**Issue by katefarrar** [elastic/observability-design#13]
### Metrics Audit
Reviewing: [Node details view](https://github.com/elastic/metrics/issues/20)

Related master audit issue [#7](https://github.com/elastic/observability-design/issues/7)

🐛 Bugs
- When a node name wraps to another line, the tab navigation is cut off vertically:
<img width="713" alt="Screen Shot 2020-12-10 at 2 25 08 PM" src="https://user-images.githubusercontent.com/455281/101831690-84898100-3af3-11eb-9629-3beacd4a2f5c.png">

Note: @hbharding covered everything else I found in this [PR](https://github.com/elastic/kibana/pull/85044) and [audit](https://github.com/elastic/kibana/issues/85061)

**Comment by hbharding** [comment]
This issue is fixed in my PR.

**Comment by katrin-freihofner** [comment]
> This issue is fixed in my PR.

@hbharding can you link the PR?

**Comment by katrin-freihofner** [comment]
@katefarrar what is the progress on this one?

**Comment by katefarrar** [comment]
here is the PR: https://github.com/elastic/kibana/pull/85044

this is resolved.
