### ISSUE TITLE
[Audit/7.11] Logs UI

### ISSUE THREAD

**Issue by hbharding** [elastic/observability-design#15]
Related master audit issue https://github.com/elastic/observability-design/issues/7

### Context menu button

- [x] Clicking the `...` button a 2nd time (or double clicking) causes the menu to persist https://github.com/elastic/kibana/issues/85823

<details>
<summary>View screens</summary>

![Kapture 2020-12-10 at 17 58 47](https://user-images.githubusercontent.com/847805/101840136-8e21e180-3b11-11eb-9d3e-d270233230c9.gif)

</details>

- [ ] Scrolling while context menu is open detaches menu from button. The context menu should scroll with the button. https://github.com/elastic/kibana/issues/85825

<details>
<summary>View screens</summary>

![Kapture 2020-12-10 at 18 28 17](https://user-images.githubusercontent.com/847805/101842184-7e0c0100-3b15-11eb-9be1-9b52b880f720.gif)

</details>

### Context menu padding

- [x] Add `paddingSize='none'` to EuiPopover. Note: this seems to happen in a few other places. PR: https://github.com/elastic/kibana/pull/86764

<details>
<summary>View screens</summary>

**What our's looks like + our code**
![image](https://user-images.githubusercontent.com/847805/101841928-f4f4ca00-3b14-11eb-836c-331f78af8d89.png)
![image](https://user-images.githubusercontent.com/847805/101841468-f70a5900-3b13-11eb-901b-146936af4cd7.png)

**From EUI docs**
![image](https://user-images.githubusercontent.com/847805/101842263-aa278200-3b15-11eb-8d34-ae907619c87b.png)
![image](https://user-images.githubusercontent.com/847805/101842292-b9a6cb00-3b15-11eb-9d07-2b56bfd3d848.png)

Another place i've seen this:

![image](https://user-images.githubusercontent.com/847805/101842412-f8d51c00-3b15-11eb-9f94-1a0d6f9a877b.png)

</details>

### Settings

- [x] Log columns are not aligned. Add `alignItems='center'` to flex group PR: https://github.com/elastic/kibana/pull/86764

<details>
<summary>View screens</summary>

![image](https://user-images.githubusercontent.com/847805/101839044-adb80a80-3b0f-11eb-9f9e-cda24498d975.png)

</details>

### Inconsistency with date time picker layout between ML tabs

- [x] Remove the paneling on the Categories tab. Also, remove the empty FlexItem which is causing unnecessary spacing?

PR: https://github.com/elastic/kibana/pull/86769
Issue: https://github.com/elastic/kibana/issues/86771

<details>
<summary>View screens</summary>

Category Tab
![image](https://user-images.githubusercontent.com/847805/101843950-48691700-3b19-11eb-923c-03ef37971f06.png)

Anomaly tab
![image](https://user-images.githubusercontent.com/847805/101843990-5880f680-3b19-11eb-93a4-b22f9903e2e1.png)

Unused flex item. Perhaps this is used for an EuiCallout? If that's the case, we should change it so the flex item is conditionally shown.
![image](https://user-images.githubusercontent.com/847805/101844108-aeee3500-3b19-11eb-8a29-86520890e7c5.png)

</details>

**Comment by katrin-freihofner** [comment]
Thank you @hbharding these are very valid points. I'm going to report the bugs and will fix the other issues after FF.
