### ISSUE TITLE
[APM] Design Service Overview actionability improvements

### ISSUE THREAD

**Issue by alex-fedotyev** [elastic/observability-design#20]
## Summary of the problem

This improvement will introduce minor enhancements to the APM service overview page to make it more actionable.
Currently, service overview page provides a lot of important information, but it is not always possible to act on it, like filter by key attributes or drill down to other observability pages.

## User stories

- As app ops troubleshooting production issues, I want to quickly narrow down my analysis of a service performance to view particular subset of the service to confirm whether it has problems or not, like service version, runtime version, cloud available zone, etc.
- As app ops troubleshooting production issues, I want to quickly drill down into the instance details when seeing that the instance is performing poorly.

## Prototype

![image](https://user-images.githubusercontent.com/4104278/105961258-8f39ae80-607e-11eb-978f-360f5e5acff1.png)

[Whimsical](https://whimsical.com/service-overview-improvements-4LjqhHx3KRemMpTNtmogim)

## Deliverables

Hi-fi mockups to define the changes in design for implementation in the next cycle.

**Comment by formgeist** [comment]
### Design update - Feb, 9

I just wanted to share a quick video with the design updates to the Service overview that we're proposing in the coming cycle.

**Update summary**
- Changed the service icons to visually present as buttons
- Updated the header layout a bit to accommodate the new Correlations option and transaction type selector
- Instances distribution now has a larger full-width panel to show the visualization.
- The comparison in instances is now clearly indicated by changing the symbol used to visualize the comparison period.

▶️ [Figma prototype](https://www.figma.com/proto/a7f2qHIWDklzmbWlzTKnh4/20-%2F-Service-overview-V2?node-id=1901%3A41479&viewport=196%2C-741%2C0.13578000664710999&scaling=min-zoom)

https://user-images.githubusercontent.com/4104278/107347187-d9cb1a00-6ac5-11eb-8c5f-e3bffc989bbc.mp4

**Comment by formgeist** [comment]
Closing as I've created [all implementations issues](https://github.com/elastic/kibana/labels/apm%3Aservice-overview-actions) for these enhancements
