### ISSUE TITLE
[APM] Fleet: Design edit configuration view to support server and language agents settings

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-design#29]
Related Kibana issue https://github.com/elastic/kibana/issues/91412

# Summary

In conjunction with enabling users to set up the Elastic APM agent and in the future manage language agents through the Fleet UI available.

Also in scope for this issue:
- APM Agent manual installation instructions
- Java agent runtime attachment UI

The current state of the editor looks like;

![screencapture-localhost-5601-lmu-app-fleet-2021-03-05-10_57_34](https://user-images.githubusercontent.com/4104278/110128735-6f0cb600-7dc7-11eb-8cf7-ef9359540f7e.png)

**Comment by simitt** [comment]
When running on cloud, not all config options will be allowed to be managed by the user. Most probably every configuration option on a dedicated policy will have a flag indicating whether or not it can be changed. The editor should be able to handle this accordingly.

**Comment by formgeist** [comment]
I wonder if it would make sense to create a spreadsheet with the various config options and also add the various agent options in there? I think that’ll only benefit us down the line as well. Unless something like this already exists?

**Comment by simitt** [comment]
Yes, I started with such a spreadsheet already, will share here beginning next week.

**Comment by formgeist** [comment]
@simitt Awesome, thanks!

**Comment by felixbarny** [comment]
For the APM Agent installation instructions and attachment options, I did some mockups here: https://docs.google.com/document/d/1b_Fy0KcgQBer_jQpgCjVaIbsg8--oGX_XqNy6mSONsU/edit#heading=h.anm90f6sm6di

**Comment by formgeist** [comment]
**Design update – 1 July, 2021**

The redesign of the APM integrations settings page's main changes will be consisting of re-organizing the relevant configurations in groups that relate mostly to features to be set in the integrations to unlock end-user features or allow for configuring the defaults set in the server.

![03b Fleet - APM integration - Settings (default)](https://user-images.githubusercontent.com/4104278/124172878-a4da5680-daaa-11eb-8504-a780f7526090.png)

Each group section will have a title and description in the panel header and the contents listed as described forms.

Additionally, we'll style the inputs as read-only when these are non-editable by the selected policy (Cloud-managed Fleet).

<details>
<summary>View full unfolded view</summary>

![03b Fleet - APM integration - Settings (all open)](https://user-images.githubusercontent.com/4104278/124172888-a9067400-daaa-11eb-8273-46b49583b6fe.png)

</details>

Moving to implementation issue https://github.com/elastic/kibana/issues/91412

**Comment by felixbarny** [comment]
Is there a follow-up issue that handles the APM Agents tab including the attach options and manual installation instructions?

**Comment by formgeist** [comment]
@felixbarny I've created https://github.com/elastic/observability-design/issues/77 to continue to track this design. I'll share more in that as I follow up from where we left off.
