### ISSUE TITLE
[Observability] Solution navigation: Define implementation details

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-design#31]
# Summary

Based on the initial structure that was decided in https://github.com/elastic/observability-dev/issues/1242#issuecomment-804701649, we need to detail how the individual apps will solve their nested navigation beyond the first level which is now present in the side navigation. This mainly involves Metrics and APM which have nested navigation beyond the first level for selected services and node detail views.

![image](https://user-images.githubusercontent.com/4104278/112113856-a648d880-8bb7-11eb-8916-7ddb29e49b2e.png)

Note: Settings views will not be consolidated in the first iteration (targeting 7.14) but will each individual app's settings view will be available from the menu actions in the top right in the Kibana header.

<img width="1437" alt="Screenshot 2021-03-23 at 09 13 44" src="https://user-images.githubusercontent.com/4104278/112114398-50286500-8bb8-11eb-9e48-6754d2a202a8.png">

# Considerations

- **UX app**: Filters are currently presented in a sidebar component which eventually will squeeze the content even narrower. Possible solution is to consider moving the filters to the header in a horizontal layout instead.
- **Smaller viewports**: What happens on smaller viewports? Do we collapse it into a popover on smaller screens to accommodate for the content.

# Deliverables

- Define implementation issues for each app in order to support the new navigation

**Comment by katrin-freihofner** [comment]
I'm not sure what you mean with smaller viewports. There is a mobile version of the navigation:
![mobile](https://user-images.githubusercontent.com/20965076/112116684-d0e86080-8bba-11eb-972b-8675aade0ccc.gif)

**Comment by formgeist** [comment]
I think what was referred to was another breakpoint for smaller desktop sizes, not mobile, where the content will be very narrow if the sidenav is always displayed. Not sure if we would consider a step between the mobile and default display.

![screencapture-cchaos-github-io-kibana-8-nav-observability-trace-2021-03-23-09_36_12](https://user-images.githubusercontent.com/4104278/112117157-53712000-8bbb-11eb-9be0-fc922447c1ae.png)

**Comment by formgeist** [comment]
I think the underlying issue perhaps isn't how the navigation will respond, but how our layouts are responding to the smaller viewport.

**Comment by formgeist** [comment]
**Design update - Mar 30**


https://user-images.githubusercontent.com/4104278/112991394-5a71d280-9167-11eb-8feb-a61722e3d9f2.mp4

@katefarrar and myself have been adding onto our Figma files with examples of the new sidenav in conjunction with the different layouts that we have in our various apps. This has shown that beyond adding the new sidenav, we will need to accommodate some changes to the layouts depending on how we want to present certain controls and allowing the responsive guidelines to shape the layout now that we have less real-estate on smaller viewports with a static sidenav.

We've put together a quick video above that showcases the prototype of navigating the sidenav links and the varying layouts. The details of each app is not yet clear, but we have been making some early ideas and converted some elements to new header controls etc. We'll keep everyone updated on these as we make additional progress.

📌 [Figma prototype](https://www.figma.com/proto/VcfpX65sUVmST9iFKKtX2G/31-Solution-navigation?node-id=1%3A87&viewport=366%2C-333%2C0.5&scaling=min-zoom)

cc @elastic/observability-design @cchaos

**Comment by formgeist** [comment]
Closing out this initial design issue since we have defined the implementation details of the side nav in https://github.com/elastic/kibana/issues/98212 and any further design issues should be opened as new issues.
