### ISSUE TITLE
[Fleet] Designs for restricting actions related to hosted agent policies

### ISSUE THREAD

**Issue by hbharding** [elastic/observability-design#32]
@jfsiii I'm posting updated designs related to your questions asked here https://github.com/elastic/kibana/issues/91906 and here https://github.com/elastic/kibana/issues/90437

cc @mostlyjason 

As a recap, we need to restrict certain actions in the Fleet UI related to 1) hosted agent policies and 2) agents that are enrolled with a hosted agent policy. We also need to account for and restrict bulk actions that might include "hosted" agents. Below is a summary of what we should account for, along with screenshots + descriptions of behavior.

- [x] 1. Provide a visual indicator + description informing users if a policy is "hosted"
- [x] 2. Agents enrolled in a hosted agent policy cannot be upgraded, unenrolled, or reassigned to a new policy
- [x] 3. Agents enrolled in a hosted agent policy should not be marked as "upgrade available" if using an earlier agent version
- [x] 4. Agents cannot be enrolled with a hosted agent policy.
- [x] 5. Users cannot delete or copy hosted agent policies
- [x] 6. Users should not be able to revoke an enrollment token used by a hosted agent policy
- [x] 7. Users cannot add or remove integrations from a hosted agent policy
- [x] 8. Bulk actions - users should not be able to select agents enrolled in a hosted agent policy

---

## 1. Provide a visual indicator + description informing users if a policy is "hosted"

On the Agent policy detail page, as well as any other place we display a link to the hosted agent policy, show an icon with hover tooltip:
> **Title**: Hosted agent policy
> **Text**: This policy is managed outside of Fleet by a hosting service, such as Elastic Cloud. Please make changes through your hosting service

<details><summary>screenshots</summary>

**Agent policy detail page**
**Note:** Use a 24px "lock" icon (`size="l"`) with `subdued` color
![image](https://user-images.githubusercontent.com/847805/113349279-c9852d80-9305-11eb-9034-c6a7f501d007.png)

**Agent policy table**
**Note:** Use a 16px "lock" icon (`size="m"`) with `subdued` color
![image](https://user-images.githubusercontent.com/847805/113349046-77dca300-9305-11eb-9c45-5188f6d1eb36.png)

**Agents table**
![image](https://user-images.githubusercontent.com/847805/113348891-31874400-9305-11eb-805a-325aa970ab0c.png)

</details>

## 2. Agents enrolled in a hosted agent policy cannot be upgraded, unenrolled, or reassigned to a new policy

- On the agents table, remove all actions except for "View agent"
- On the agents detail page, remove the "actions" button in the page header (top right) since all actions inside the button are not available.

<details><summary>screenshots</summary>

**Agents table**
**Note:** this context menu also appears on the agent detail page, but I believe this is a shared component so should only need to be accounted for in one place in the code.
![image](https://user-images.githubusercontent.com/847805/113349356-e6b9fc00-9305-11eb-8f63-5cb223b5a616.png)

</details>

## 3. Agents enrolled in a hosted agent policy should not be marked as "upgrade available" if using an earlier agent version

Simply do not show the yellow "alert" icon + text if the agent is running an earlier version. In addition, the agent should not appear in the table if the user clicks the "Upgrade available" filter button.

## 4. Agents cannot be enrolled with a hosted agent policy.

- On the agent policy list page, remove the "add agent" action which appears in the [...] actions menu
- On the agent policy detail page, remove the "add agent" action which appears in the page header "actions" button
- In the Add Agent flyout, do not show hosted agent policies in step 2 where users are asked to "choose an agent policy"

## 5. Users cannot delete, copy, or rename a hosted agent policy

- Do not show the “Delete policy” section for Hosted agent policies which typically appears under the “Agent monitoring” section. Related: https://github.com/elastic/kibana/issues/95226
- Disable the "name" and "description" inputs.
- Do not show the "copy policy" action which appears in two places
  - On the agent policy detail page, in the "actions" button that appears in the page header
  - On the agent policy list page, in the [...] actions menu

<details><summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/847805/113350732-d571ef00-9307-11eb-8a12-e7b5319750c7.png)

</details>

## 6. Users should not be able to revoke an enrollment token used by a hosted agent policy

- Do not show the the "revoke token" trash icon

<details><summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/847805/113350860-0ce09b80-9308-11eb-86ae-676164bbbb0d.png)

</details>

## 7. Users cannot add or remove integrations from a hosted agent policy

- On the agent policy detail page integration's tab, hide the "Add integration" button
- On the same page, hide the "delete integration" action which appears in the [...] actions menu in the Integrations table
- From an Integration detail page, when users click "Add IntegrationName", do not show hosted agent policies in the step where users are asked to select an agent policy. This will prevent users from being able to add integrations to hosted agent policies.

<details><summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/847805/113351205-84aec600-9308-11eb-8405-42ee1318b143.png)

</details>

## 8. Bulk actions - users should not be able to select agents enrolled in a hosted agent policy

- As we discussed in Slack, we can disable the checkbox for agents enrolled in a hosted agent policy. We don't need to provide a tooltip description since the Agent policy "lock" icon appears in the table row.
- If a user selects the top-left checkbox to select all agents on the page, and then clicks "select everything on all pages", we don't need to provide a count for total number of agents selected. The bulk actions button can say "all agents selected" (as discussed, calculating the total number of agents is problematic and can be tough on performance). Choosing a bulk action should filter out / not include any agents that are enrolled in a hosted agent policy.
- Related to calculating total number of agents, we previously showed a count in the action modal's title. In the case where users have selected everything on all pages, the title can just say "all selected agents" -> i.e. "upgrade all selected agents"
- **Unrelated to hosted agents, but some things we discussed on Slack for minor improvements:**
  - If the result of a bulk action has mixed results, as in some percentage of agents are successful but others fail, show a warning toast that indicates how many succeeded and how many failed. See screenshot below.
  - The "assign to new policy" action should display in a modal rather than a flyout to be consistent with the other bulk actions. (Originally discussed here https://github.com/elastic/kibana/issues/90437 - disregard the warning callouts in those screenshots)
  - Change the "experimental" badge for the upgrade agent action modal to be an icon only badge to help avoid word wrapping. You can use the `beaker` icon. The badge should use the same tooltip description that we use today indicating that this action is experimental.
 
<details><summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/847805/113351904-8d53cc00-9309-11eb-8347-9a630778150b.png)
![image](https://user-images.githubusercontent.com/847805/113351934-980e6100-9309-11eb-9f8e-10e6b003446b.png)

**Warning toast for partial results**
![image](https://user-images.githubusercontent.com/847805/113353547-d73db180-930b-11eb-82ed-ab18bed4dd7d.png)

</details>

**Comment by jfsii** [comment]
^ @jfsiii

**Comment by mostlyjason** [comment]
Thanks Henry!

**Comment by hbharding** [comment]
@jfsiii I updated this issue based on some of the things we discussed. The big change is that instead of disabling actions (as originally described), we'll simply not show them. The reason being that users cannot take any action to un-disable them, so it's better to hide. The "lock" icon for the hosted agent policies gives a visual indicator and description for why these actions are missing.

**Comment by mostlyjason** [comment]
@hbharding Can we provide more context on why these actions are not available and what actions the user should take? What about this?
> This policy is managed outside of Fleet by a hosting service, such as Elastic Cloud. Please make changes through your hosting service. 

In the warning toast can we say:
> Assigned 8 of 10 agents to a new policy. 2 agents could not be reassigned because they are managed by a hosting service.

**Comment by hbharding** [comment]
@mostlyjason I'm not sure which actions you're referring to. Actions related to hosted agent policies are not visible in UI. Do you mean the disabled checkbox on the agents table, which appears next to hosted agents? If so, I don't think it's necessary to describe the disabled checkbox in a separate tooltip since there is a lock icon next to the hosted agent policy name which provides a description:
> This policy is managed outside of Fleet. Most actions related to this policy are unavailable.

We have similar behavior for agents that are `inactive`. Disabled checkbox / no description.

The warning toast / partial failure is unrelated to hosted agents. It's not possible for users to bulk select hosted agents (hence the disabled checkbox), so the reason for a failed action won't be because the agent is hosted. @jfsii discovered that our current behavior for bulk actions (on regular agents) is that if 100 agents succeeded and 5 agents failed, we would show a failure toast that said "Failed to do X" when in fact some succeeded. I had originally designed bulk actions to account for "partial success" scenarios but it wasn't implemented. John said it would be an easy fix to get in and wanted a place to reference it. Apologies for mixing it into this issue.

**Comment by mostlyjason** [comment]
@hbharding I was thinking that text could be shown in the hovertext of for the lock icon. What do you think? 

> This policy is managed outside of Fleet by a hosting service, such as Elastic Cloud. Please make changes through your hosting service.

![image](https://user-images.githubusercontent.com/6370704/113776976-5bfb4780-96df-11eb-9cb9-83543f9e0d1f.png)

**Comment by hbharding** [comment]
Oh sorry, misunderstood that. Sure, that sounds fine. I'll update above

**Comment by jfsiii** [comment]
@mostlyjason @hbharding I used that text in https://github.com/elastic/kibana/pull/96337 (aside from "hosted" which is coming in follow up)
