### ISSUE TITLE
[Audit] Synthetics 7.13

### ISSUE THREAD

**Issue by katefarrar** [elastic/observability-design#49]
# Synthetics Audit

Tested on: `master` on `edge`

### Docs icon is repeated when "body size recorded content" is shown
<img width="736" alt="Screen Shot 2021-05-03 at 8 30 41 PM" src="https://user-images.githubusercontent.com/455281/116955073-ca83e480-ac4e-11eb-8b19-7d44a74dd34e.png">

___

### Page content isn't full-width, but expands to fill the container of the page when you expand an item in the History table
<img width="1792" alt="Screen Shot 2021-05-03 at 8 36 53 PM" src="https://user-images.githubusercontent.com/455281/116955290-58f86600-ac4f-11eb-9f29-4be51eb50c29.png">
<img width="1788" alt="Screen Shot 2021-05-03 at 8 36 24 PM" src="https://user-images.githubusercontent.com/455281/116955292-5a299300-ac4f-11eb-9fae-874eb1354186.png">

___

### Inconsistent page widths
<img width="1792" alt="Screen Shot 2021-05-03 at 8 40 27 PM" src="https://user-images.githubusercontent.com/455281/116955463-d58b4480-ac4f-11eb-9216-fb40e637183c.png">
<img width="1792" alt="Screen Shot 2021-05-03 at 8 40 21 PM" src="https://user-images.githubusercontent.com/455281/116955465-d7ed9e80-ac4f-11eb-8185-e82e98646603.png">

___

### Header items not aligned
_This might be an issue with the page widths_
<img width="1019" alt="Screen Shot 2021-05-03 at 8 29 21 PM" src="https://user-images.githubusercontent.com/455281/116955633-52b6b980-ac50-11eb-896d-28f3f462da01.png">

___

### Step 2 of 2 is wrapping to the next line in waterfall step view
<img width="1030" alt="Screen Shot 2021-05-04 at 9 01 11 AM" src="https://user-images.githubusercontent.com/455281/117024627-65b0a480-acb7-11eb-8922-b9cdd0c5a6bd.png">

___

### Steps view thumbnail text in lightbox is very hard to read
`Step 1 of 2` and timestamp text is white on white
<img width="1042" alt="Screen Shot 2021-05-04 at 11 08 08 AM" src="https://user-images.githubusercontent.com/455281/117042362-1a06f680-acc9-11eb-87ee-237a7a851569.png">

___

### Exploratory view - Uptime (or User Experience) should be included in the Breadcrumbs
When you are in the Exploratory view there is no way to get back to the previous app - Uptime or User Experience (depending on where the user navigated from) should be included in the breadcrumbs
<img width="406" alt="Screen Shot 2021-05-04 at 9 18 50 AM" src="https://user-images.githubusercontent.com/455281/117042506-50dd0c80-acc9-11eb-8520-b6eff84ffa58.png">

___

###  Exploratory view - instructions aren't clear
Instructions say to `Select a report type to create a visualization.` but once you select a report type there is still no data. The user must then select something in `Definition` to see data. Instructions should clarified or steps should be shown. For example:
`Select a report type and then choose a definition to create a visualization.`
Or maybe break down the instructions into steps:
`To create a visualization:
Step 1: Choose data type
Step 2: Choose report type
Step 3: Choose a definition`

https://user-images.githubusercontent.com/455281/117044821-17f26700-accc-11eb-9aa6-b4310b32d7e5.gif

**Comment by katrin-freihofner** [comment]
@katefarrar do you see these as bugs or enhancements? Did you have a chance to review the exploratory view as well?

**Comment by katefarrar** [comment]
> @katefarrar do you see these as bugs or enhancements? Did you have a chance to review the exploratory view as well?

I changed those from Bugs to Enhancements - good call. Also, going to review and add notes on the Exploratory view now.

**Comment by formgeist** [comment]
@liciavale Would you have a chance to review the above items and triage into issues or enhancements as you see fit? Then we can close the design audit issue. Thank you 👍
