### ISSUE TITLE
[APM] Mobile APM entry points to Exploratory view

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-design#50]
## Summary of the problem

As we're adding support for Mobile APM with the new iOS agent in 7.14, we want to also add the ability to utilize the Exploratory view for analyzing user demographic data such as device types, locations, and more. This means we need to add entry points to the Exploratory view from APM on the service charts that will exist for iOS.

**Telemetry**

We want to measure what charts users tend to use for analyzing their metrics further, so we can gauge which types of charts are used the most. 

## User stories

Take each of the user stories and describe this specific use case in more detail and the benefit that this feature will bring to the user.

### Example user story 1

As a user, I want to analyze my iOS data by breaking down performance data by specific dimensions available such as device type, location, and more.

----

**This section should be filled in collaboration and agreement with a designer.**

## Deliverables

Example screens that define the entry points into Exploratory view from the APM service views.

### Low-fi wireframes

<details>
<summary>View screens</summary>

![image](https://user-images.githubusercontent.com/4104278/117985432-fbdc6e80-b338-11eb-8bc2-e3534e81215b.png)

![image](https://user-images.githubusercontent.com/4104278/117985459-01d24f80-b339-11eb-9b09-15825fb88e1a.png)

</details>

**Comment by nehaduggal** [comment]
Drop the 'All Instances' table for the mobile agents - it doesn't add much value. And if theres a chart that will not populate for mobile data (at least at the moment), have a more user friendly message that says "This is not currently available for Mobile data".

**Comment by formgeist** [comment]
We'll be adding a general link to the Exploratory view from the Service header for the initial iteration. This follows the same similar pattern that we've implemented in UX and Uptime, except the option is only available from the service header.

![mobile-ui-analyze-data-links](https://user-images.githubusercontent.com/4104278/121521097-f3d52480-c9f3-11eb-99d7-78568e3325d4.png)

On hover, we'll show a tooltip explaining the feature is currently in Experimental.

![mobile-ui-analyze-data-links-tooltip](https://user-images.githubusercontent.com/4104278/121521108-f59ee800-c9f3-11eb-8d67-31f8c43e6988.png)

**Comment by formgeist** [comment]
Closing this issue and moving design into https://github.com/elastic/kibana/issues/100759 with the rest of the related changes for the first implementation.
