### ISSUE TITLE
[APM] Design: Add the sparkline charts and time comparison to additional views

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-design#52]
# Summary

We have added sparklines to the Services inventory and Service overview pages in recent releases and now it's time we bring these powerful charts to the rest of the APM views. In conjunction with adding sparklines, we'll also be adding the time comparison feature to these views.

# Design tasks

We need to figure out how we'll fit in the sparkling charts in these additional views within APM;

#### Service map: The service info popover

Existing issue for adding sparklines https://github.com/elastic/kibana/issues/77318

<img width="640" alt="Screenshot 2021-05-28 at 16 04 45" src="https://user-images.githubusercontent.com/4104278/119996007-85916a80-bfce-11eb-98fa-e7596304ec73.png">

#### Traces view 

Issue: https://github.com/elastic/kibana/issues/102871

<img width="1919" alt="Screenshot 2021-05-28 at 16 05 00" src="https://user-images.githubusercontent.com/4104278/119996040-8c1fe200-bfce-11eb-8e04-6778e406146e.png">

#### Transactions list view

Issue: https://github.com/elastic/kibana/issues/91848

<img width="1917" alt="Screenshot 2021-05-28 at 16 04 30" src="https://user-images.githubusercontent.com/4104278/119996052-904bff80-bfce-11eb-9d73-4364b5ae6501.png">

#### Errors list view

Issue: https://github.com/elastic/kibana/issues/102873

<img width="1927" alt="Screenshot 2021-05-28 at 16 04 21" src="https://user-images.githubusercontent.com/4104278/119996059-9346f000-bfce-11eb-9fb6-5b6518f2dd54.png">

#### Errors occurrence chart

Issue: https://github.com/elastic/kibana/issues/102874

<img width="1731" alt="Screenshot 2021-06-07 at 13 32 58" src="https://user-images.githubusercontent.com/4104278/121009839-ebcb7980-c794-11eb-9357-aa6b82c004db.png">

<img width="1733" alt="Screenshot 2021-06-07 at 13 33 07" src="https://user-images.githubusercontent.com/4104278/121009852-ee2dd380-c794-11eb-9f5d-3d1718b21163.png">

# Design status

- [x] Service Maps popover
- [x] Transactions list
- [x] Traces list
- [x] Errors list
- [x] Comparison: Errors occurrence chart

# Screens

![Traces](https://user-images.githubusercontent.com/4104278/122895979-e94a5180-d348-11eb-8f1b-6689f320e7ed.png)

![Errors list + occurrences chart](https://user-images.githubusercontent.com/4104278/122895990-ebacab80-d348-11eb-8eab-d3005b277390.png)

![Error group detail](https://user-images.githubusercontent.com/4104278/122896000-ee0f0580-d348-11eb-8978-950cd206454d.png)

**Comment by formgeist** [comment]
Closing as this is now complete and I've linked all related Kibana issues in the description above. Some already had existing implementation issues, so they've been linked too.

cc @alex-fedotyev

**Comment by alex-fedotyev** [comment]
I think we missed here the view for the transaction itself, or at least I can't find the design for it anywhere :( 

I mean following page, when you are looking at particular transaction:
![image](https://user-images.githubusercontent.com/61838744/125362397-ab2ac700-e323-11eb-838d-a1e5bd6255ce.png)

**Comment by alex-fedotyev** [comment]
I am only able to find the designs which were part of transaction overhaul work, and they would probable fit our purpose well.
![image](https://user-images.githubusercontent.com/61838744/125375273-a1ae5880-e33d-11eb-8af5-2fb03820738f.png)

**Comment by alex-fedotyev** [comment]
I suggest following priorities in the implementation:

1. Services inventory
2. Transaction view and transactions list
3. Errors
4. Service map popups
5. Traces
