### ISSUE TITLE
[Observability] Design the breadcrumb pattern for all apps

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-design#53]
# Summary

We're implementing the new Solution navigation will make navigating the entire solution much easier and consistent. In conjunction with this implementation, we're trying to figure out a consistent pattern for all apps to implement with regards to the breadcrumbs.

# Challenges

### 1. Displaying the app name in the breadcrumb

The primary challenge is that we want to display the app name within the breadcrumb nested levels to ensure that the user knows which app this view belongs to. We have several Overview pages, so simply stating `Observability > Overview` can be confusing.

Each app has a designated landing page based on the Kibana navigation where the user can click any of the app names and it will send them to the first page within the navigation structure for that app.

<img width="305" alt="Screenshot 2021-05-31 at 13 16 05" src="https://user-images.githubusercontent.com/4104278/120185358-5f5c0c80-c212-11eb-9146-d6311d7ad9a0.png">

In turn, the breadcrumb list will look like this, making the APM app clickable as it will go to the Services list since this is the primary landing page for the app.

![apm-example-breadcrumb](https://user-images.githubusercontent.com/4104278/120185578-afd36a00-c212-11eb-85fb-33a5e81334b7.png)

### 2. Observability is the root app for all

We want to emphasize that all of these individual apps are within the solution name Observability. This already displayed in the solution navigation as the header before the navigation. The challenge is if we want to adopt the Observability name in the root of all of the breadcrumbs. That would mean that the Observability overview becomes the go to landing page of Observability from that link in the breadcrumb. It might be redundant information and navigation but I'd like to hear what others think.

![Breadcrumbs](https://user-images.githubusercontent.com/4104278/120186037-40aa4580-c213-11eb-833b-bc1474d8c03a.png)

**Examples of breadcrumb lists for all apps**

_Logs_

Observability > Logs > Stream

_Metrics_

Observability > Metrics > Inventory

_APM_

Observability > APM > Service name > Transactions

_Uptime_

Observability > Monitoring Overview > Monitor name

_User Experience_

Observability > User Experience > Overview

Thoughts @elastic/observability-design on this? Feel free to add more challenges or patterns to make consistent within the breadcrumbs.

**Comment by formgeist** [comment]
Another thing to consider (brought to my attention by @smith) is that our page titles are also not aligned and perhaps this as good an opportunity as ever to align on those. 

<img width="415" alt="Screenshot 2021-06-16 at 09 05 13" src="https://user-images.githubusercontent.com/4104278/122173399-fa471e80-ce81-11eb-8c5c-04c603de0f5a.png">

<img width="359" alt="Screenshot 2021-06-16 at 09 06 08" src="https://user-images.githubusercontent.com/4104278/122173531-1ba80a80-ce82-11eb-93a0-d91c12f34605.png">

I prefer to show context and not just list the active page. My proposal would be they should follow the breadcrumb structure but reversed so the active page is the first label in the line.

Most commonly we use a `-` to divide, but the `|` makes the spacing a little tighter especially for longer breadcrumbs.

### APM example

**Breadcrumb**: `Observability` > `APM` > `opbeans-python` > `Transactions`
**Page title**: Transactions | opbeans-python | Services | APM | Observability | Elastic

### Uptime example

**Breadcrumb**: `Observability` > `Uptime` > `Monitoring Overview` > `My monitor`
**Page title**: My monitor | Monitoring Overview | Uptime | Observability

**Comment by katrin-freihofner** [comment]
@formgeist I think showing `Observability` in the breadcrumb makes sense and is consistent with the other solutions. I'm still not convinced we need the app name, but going that way and having a consistent pattern is already a huge improvement.

I think your page title proposal makes sense.

Quick question about these examples: why is not `opbeans-python` the first item?
 
> ### APM example
> **Breadcrumb**: `Observability` > `APM` > `opbeans-python` > `Transactions`
> **Page title**: Transactions | opbeans-python | Services | APM | Observability | Elastic
> 
> ### Uptime example
> **Breadcrumb**: `Observability` > `Uptime` > `Monitoring Overview` > `My monitor`
> **Page title**: My monitor | Monitoring Overview | Uptime | Observability

**Comment by formgeist** [comment]
> @formgeist I think showing `Observability` in the breadcrumb makes sense and is consistent with the other solutions. I'm still not convinced we need the app name, but going that way and having a consistent pattern is already a huge improvement.

It is a conservative approach by keeping the APP name present. I do agree eventually we'll probably do away with it the more the apps intertwine and the context is less about the apps but the data and the data views you're on.

> Quick question about these examples: why is not `opbeans-python` the first item?

> > ### APM example
> > **Breadcrumb**: `Observability` > `APM` > `opbeans-python` > `Transactions`
> > **Page title**: Transactions | opbeans-python | Services | APM | Observability | Elastic

Because Transactions is the currently selected view in the selected service. If the user would go to Errors or Metrics the page title would look like this;

Errors | opbeans-python | Services | APM | Observability | Elastic

Does that make sense?

**Comment by smith** [comment]
With page titles, the recommended way to use them is with [`core.chrome.docTitle.change`](https://github.com/elastic/kibana/blob/35e10ba77013715e381a2373790d67d94df825f1/docs/development/core/public/kibana-plugin-core-public.chromedoctitle.change.md), which takes an array of strings and sets the title using " - " as a separator.

**Comment by formgeist** [comment]
> With page titles, the recommended way to use them is with [`core.chrome.docTitle.change`](https://github.com/elastic/kibana/blob/35e10ba77013715e381a2373790d67d94df825f1/docs/development/core/public/kibana-plugin-core-public.chromedoctitle.change.md), which takes an array of strings and sets the title using " - " as a separator.

Ah good to know - that's a minor detail (and perhaps something to discuss in another thread), but thanks for pointing this out. I've updated my proposal above accordingly.

**Comment by formgeist** [comment]
Closing as I've opened issues for implementing the root reference to Observability for APM, Logs, and Metrics. UX and Uptime have already implemented this.

- APM issue https://github.com/elastic/kibana/issues/102900
- Logs & Metrics issue https://github.com/elastic/kibana/issues/102907
