### ISSUE TITLE
[Observability] Solution navigation: Proposal to move Settings links to the new side navigation

### ISSUE THREAD

**Issue by formgeist** [elastic/observability-design#54]
# Summary

Initially, we weren't going to do any re-organization of the individual settings pages for each app. For APM this means unless we re-design the settings navigation, we'll have double side navigation like so;

<img width="1736" alt="Screenshot 2021-06-03 at 11 57 59" src="https://user-images.githubusercontent.com/4104278/120626450-f4554480-c462-11eb-8924-144850ad69b8.png">

We can work on changing the navigation for a minor or two, but the Settings link in APM won't be consistent anywhere else. Logs, Metrics, and Uptime all have their own settings pages but no navigation in them. Eventually, we'd consider consolidating a lot of the individual settings pages in one experience.

# Proposals

### A: Move all Settings links to the side navigation

Together with @sqren I've discussed another approach that we could consider implementing which involves adding each Setting page link to the side navigation instead of the Kibana header menu links. This enables APM to have nested navigation links there as well while the rest can simply link to their respective pages.

<details>
<summary>View screens</summary>

<img width="1468" alt="A_ APM - Services" src="https://user-images.githubusercontent.com/4104278/120627197-b6a4eb80-c463-11eb-8e15-fbee48bb7cbd.png">
<img width="1468" alt="A_ APM - Settings" src="https://user-images.githubusercontent.com/4104278/120627206-b9074580-c463-11eb-8a51-cb66e6772252.png">

</details>

### B: Group Settings links in a new section in the side navigation

Alternatively, we could group all Settings pages into one section named "Settings" which is closer to a consolidated Settings view.

<details>
<summary>View screens</summary>

<img width="1468" alt="B_ Grouped settings - APM - Services" src="https://user-images.githubusercontent.com/4104278/120627302-d0dec980-c463-11eb-88a0-420d44a6c567.png">
<img width="1468" alt="B_ Grouped settings - APM - Settings" src="https://user-images.githubusercontent.com/4104278/120627313-d3d9ba00-c463-11eb-922a-bdfecde24c34.png">

</details>

### C: Switch the APM Settings navigation to use tabs available in the page template

Finally, there's the option of adopting the tabs navigation in the Settings page template for APM.

<details>
<summary>View screens</summary>

<img width="1468" alt="C_ Tabbed navigation - APM - Settings" src="https://user-images.githubusercontent.com/4104278/120628908-84948900-c465-11eb-908d-f733b2d6379a.png">

</details>

IMO, the most obvious one is the first option to simply link to Settings in the side navigation rather than having the link in the top right. Thoughts? @elastic/observability-design @sqren

**Comment by formgeist** [comment]
If you're reading this from email please check the description of the issue again, made some additional changes 👍

**Comment by katefarrar** [comment]
I like Option C. I think it's a good use of the tabs and doesn't require us to make any additional changes in the Side Navigation.

I think we should have a broader discussion (perhaps starting with the design team) around how we handle Settings in Obs. For now I think we shouldn't make any changes to the Side Nav.

**Comment by formgeist** [comment]
> I like Option C. I think it's a good use of the tabs and doesn't require us to make any additional changes in the Side Navigation.

I tend to agree especially since it doesn't involve needlessly moving other parts around.

> I think we should have a broader discussion (perhaps starting with the design team) around how we handle Settings in Obs. For now I think we shouldn't make any chang es to the Side Nav.

We have an open design issue for discussion here https://github.com/elastic/observability-design/issues/3

**Comment by formgeist** [comment]
I think we'll close this and move on with changing the APM settings navigation to use the PageHeader tabs as proposed in Option C (https://github.com/elastic/kibana/issues/101384). We'll work towards getting consensus on what should happen with a consolidated Settings view.
