### ISSUE TITLE
[APM] Integrating Correlations in the APM Service Transactions Screen 

### ISSUE THREAD

**Issue by cyrille-leclerc** [elastic/observability-design#75]
## Summary of the problem

The Transaction latency correlations feature is not easy to discover and not easy to use for Root Cause Analysis because it is presented as a Fly Out.

We propose to integrate the Transaction Correlations in the APM Service Transactions screen to 
* help discoverability of the feature
* integrate the feature in the Root Cause Analysis (RCA) workflows

## User Stories

Note: we call "operator" the person who is conducting an investigation on a performance problem

The primary role of transaction correlations in RCA workflows is to automatically propose to the analysts some hypothesis on the contributing factors to the problem he is investigating.
The operator can search for additional hypothesis slicing and dicing the observability data.

To verify his hypothesis, the operator refines the search criteria of the distributed traces to look at some of them.

### User Story : Root Cause Analysis

Context:
* Ecommerce web site
* The SRE "Joe" is on call to monitor the site

Joe is investigating on problems to pass orders on the eCommerce site. 

Joe identified a high error rate on the "createOrder" transaction

<img width="300px" src="https://user-images.githubusercontent.com/459691/126500998-12f1a1f6-359c-4d4d-9b57-5adaafe3a46c.png">

Navigating to the transaction view, the latency distribution indicates that there is a slow population of requests

<img width="300px" src="https://user-images.githubusercontent.com/459691/126500822-c67f3dd9-e257-4ce1-9bb9-4e4a5278c9a0.png" />

Transaction Latency Correlations will indicate that there is a correlation between the slowness and the business attribute `orderPriceRange: large`

<img width="300px" src="https://user-images.githubusercontent.com/459691/126501381-c1506b8d-06eb-44bb-b66b-8f2b51fee4b9.png" />

## Mockup

![image](https://user-images.githubusercontent.com/459691/126486976-baa58524-6199-42c4-82f1-5e4d6e899683.png)

Action items on the mockup

## See Also 

* #69

**Comment by cyrille-leclerc** [comment]
[APM UI Weekly Meeting(https://docs.google.com/document/d/1maSVtDa8XUfgdsTzBNcpriai3cNJLUeHU8g-IO_APcw/edit#bookmark=id.a7z3k8u27j6k)
Decisions
* We are interested in manually triggering the generation of the correlations rather than generating on page load because it may be a long task consuming resources ==> need to design a state of the fragment with an "Analyze" button (or equivalent)
* Need to understand the UX when a cluster has a license lower than Platinum and this is not eligible to the correlations feature
* The customization of the list of analyzed trace attributes is postponed
Action items:
* Design the UX
   * when the analysis of correlations has not been triggered with an "analyze" button or equivalent
   * when the cluster is not eligible to the correlations features because the license is lower than platinum

**Comment by formgeist** [comment]
**Design update – August 12, 2021**

Just a quick summary of the updated design and UX for integrating the latency and failed transaction correlations into the transaction group detail page.

![distribution-show-tip-to-select](https://user-images.githubusercontent.com/4104278/129175369-c377d01d-f670-4fb9-8b71-70d097e08bed.png)

- [x] Removed the "View correlations" button from all views
- [x] Integrated the correlations tabs into the main Transaction group detail view
- [x] The new logarithmic latency distribution is enabled for all users in the Trace samples analysis and enabled range selection in the chart.
- [x] Showing indication of the currently selected sample

@alex-fedotyev shared a quick video describing the changes https://www.loom.com/share/879c2001befe45cdb5882275dd71fdfa

The implementation work for 7.15 latency correlations GA is tracked in https://github.com/elastic/kibana/issues/106381
